### ISSUE TITLE
[BUG]  Error: Missing required @injectable annotation in: MongoService.

### ISSUE THREAD

**Issue by hackerunet** [WandersonAlves/generator-kube-microservice-node#12]
**Describe the bug**
Fresh install, added the .env file in roots application and still got an error, I could expect something like, missing parameters or something like that if the error occurs due to missing configuration, however it just shows this error:
Error: Missing required @injectable annotation in: MongoService

FULL STACK
Debugger listening on ws://0.0.0.0:9229/40db971f-14fd-4e87-97d0-2987999825e6
For help, see: https://nodejs.org/en/docs/inspector
20:18:17 info:main: Configuring server
20:18:17 info:main: Bootstraping server

/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/reflection_utils.js:21
        throw new Error(msg);
              ^
Error: Missing required @injectable annotation in: MongoService.
    at getTargets (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/reflection_utils.js:21:15)
    at Object.getBaseClassDependencyCount (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/reflection_utils.js:93:23)
    at /home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:108:67
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:94:20)
    at /home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/planning/planner.js:136:9)
    at /home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/container/container.js:317:37
    at Container._get (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/container/container.js:310:44)
    at Container.getAll (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify/lib/container/container.js:239:21)
    at Object.getControllersFromContainer (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify-express-utils/lib/utils.js:7:26)
    at InversifyExpressServer.registerControllers (/home/hackerunet/Projects/SuperPesos/super-shoppers-datastream/maia-k-invoices/node_modules/inversify-express-utils/lib/server.js:142:35)
error Command failed with exit code 1.

**Expected behavior**
Fresh install after getting all dependencies I attempted to run the application using yarn and it runs and then crashed.

**Additional context**
Linux mint OS
Not using rabbit or redis.
my .env file has the variables declared in the env.ts file:
server_port: 27017,
mongodb_url: mongo://127.0.0.1:27017/test,
mongodb_database_name: test
mongodb_authsource: admin

**Comment by WandersonAlves** [comment]
Fixed on f29fad1
